forge "http://forget.puppetlabs.com"

mod "apt",
	:git => "git://github.com/puppetlabs/puppetlabs-apt.git"

mod "stdlib",
	:git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"

mod "concat",
	:git => "git://github.com/ripienaar/puppet-concat"

mod "firewall",
	:git => "git://github.com/puppetlabs/puppetlabs-firewall"

mod "nodejs",
	:git => "git://github.com/puppetlabs/puppetlabs-nodejs"